name: Go CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4 # Adjust to your Go version

      - name: Run go mod tidy
        run: |
          go mod tidy

      - name: Check for changes
        run: |
          git config --global user.name "Jack112-create"
          git config --global user.email "jackconroy777@gmail.com"
          if ! git diff --quiet go.mod go.sum; then
            git checkout -b go-mod-tidy-changes
            git add go.mod go.sum
            git commit -m "Fix: run go mod tidy"
            git push origin go-mod-tidy-changes
          fi
